export const appPaths = {
  home: '/',
  login: '/login',
  assets: '/assets',
  posts: '/posts',
  characters: '/characters',
  characterPosts: '/character-posts',
  users: '/users',
  videos: '/videos',
  lessons: '/lessons',
  shadowing: '/shadowing',
  integrationsTikTok: '/integrations/tiktok',
  character: (characterId: string) => `/characters/${encodeURIComponent(characterId)}`,
  videoEdit: (characterId: string, videoId: string) => `/videos/${encodeURIComponent(characterId)}/${encodeURIComponent(videoId)}/edit`,
  lessonEditor: (lessonId: string) => `/lessons/${encodeURIComponent(lessonId)}/edit`,
} as const
